# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"   # or "build" depending on your framework (Vite = dist, CRA/Next.js = build)

[dev]
  command = "npm run dev"
  port = 8888
  publish = ".next"

# Redirects (for SPA routing, e.g., React, Vue, Angular)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https: data:"
